"""Polish the release notes of an open release-please Release PR with an LLM.

Adds a short "Highlights" section and rewords the entries of the unreleased version, in both
``CHANGELOG.md`` and the Release PR description (release-please builds the GitHub Release notes
from the PR description when the Release PR is merged).

The step is optional and must never block a release: if no OpenAI key is configured, the API
call fails or the polished notes don't pass validation, the notes are left unchanged and the
script exits with 0.

Usage (see ``.github/workflows/release.yml``)::

    python scripts/polish_changelog.py --body body.md --changelog CHANGELOG.md
"""

import argparse
import json
import logging
import re
import subprocess
import sys
from pathlib import Path
from typing import Callable

LOG = logging.getLogger("polish_changelog")

NOTES_DELIMITER = "---"
HIGHLIGHTS_HEADING = "### Highlights"
MAX_GROWTH_FACTOR = 3
MAX_GROWTH_CHARS = 2000

LINK_PATTERN = re.compile(r"\]\(([^)\s]+)\)")
HASH_PATTERN = re.compile(r"\b[0-9a-f]{7,40}\b")
PR_REFERENCE_PATTERN = re.compile(r"\[#(\d+)\]")

INSTRUCTIONS = f"""\
You edit the release notes of a Python library for its CHANGELOG and GitHub Release.
You receive the generated notes of one version and, as context, the descriptions of the included
pull requests. Return the improved notes as Markdown and nothing else.

Rules:
- Keep the first line (the version heading) exactly as it is.
- Directly after the first line, add a "{HIGHLIGHTS_HEADING}" section with one short paragraph
  (at most three sentences) summarizing what matters most to users of the library.
- Keep all other "###" section headings, in the same order.
- Keep every bullet entry. You may reword the text of an entry to make it clearer for users, but
  keep every Markdown link and commit hash exactly as it is, at the end of the entry.
- Only use facts from the notes and the pull request descriptions. Do not invent anything.
- Never write a line that consists only of "{NOTES_DELIMITER}".
"""


def split_body(body: str) -> tuple[str, str, str] | None:
    """Split a Release PR description into header, notes and footer.

    Mirrors release-please's own parsing: the notes are between the first and the last line
    that consists only of ``---``.

    Returns:
        ``(header, notes, footer)`` or ``None`` if the description has no notes delimiter.
    """
    lines = body.strip().replace("\r\n", "\n").split("\n")

    if NOTES_DELIMITER not in lines:
        return None

    first = lines.index(NOTES_DELIMITER)
    last = len(lines) - 1 - lines[::-1].index(NOTES_DELIMITER)

    if last == first:
        last = len(lines) - 1

    header = "\n".join(lines[:first])
    notes = "\n".join(lines[first + 1 : last]).strip()
    footer = "\n".join(lines[last + 1 :])

    return header, notes, footer


def validate(original: str, polished: str) -> list[str]:
    """Check that the polished notes kept everything release-please and readers rely on.

    Returns:
        A list of problems; empty if the polished notes are safe to use.
    """
    problems = []
    original_lines = original.strip().split("\n")
    polished_lines = polished.strip().split("\n")

    if polished_lines[0] != original_lines[0]:
        problems.append(f"version heading changed: {polished_lines[0]!r}")

    if NOTES_DELIMITER in polished_lines:
        problems.append(f"contains a {NOTES_DELIMITER!r} line")

    if HIGHLIGHTS_HEADING not in polished_lines:
        problems.append(f"missing {HIGHLIGHTS_HEADING!r} section")

    original_sections = [line for line in original_lines if line.startswith("### ")]
    polished_sections = [line for line in polished_lines if line.startswith("### ") and line != HIGHLIGHTS_HEADING]
    if polished_sections != original_sections:
        problems.append(f"sections changed: {polished_sections} != {original_sections}")

    for link in LINK_PATTERN.findall(original):
        if link not in polished:
            problems.append(f"missing link: {link}")

    for commit_hash in HASH_PATTERN.findall(original):
        if commit_hash not in polished:
            problems.append(f"missing commit hash: {commit_hash}")

    if len(polished) > MAX_GROWTH_FACTOR * len(original) + MAX_GROWTH_CHARS:
        problems.append(f"too long: {len(polished)} characters")

    return problems


def polish(notes: str, context: str, complete: Callable[[str, str], str]) -> str:
    """Return the polished notes, or the original notes if polishing isn't possible or safe.

    Args:
        notes: The release notes of the unreleased version, as generated by release-please.
        context: Titles and descriptions of the included pull requests.
        complete: Sends ``(instructions, input)`` to the LLM and returns its answer.
    """
    if HIGHLIGHTS_HEADING in notes.split("\n"):
        LOG.info("Notes are already polished.")
        return notes

    prompt = f"# Release notes\n\n{notes}\n\n# Pull requests\n\n{context or '(none)'}"

    try:
        polished = complete(INSTRUCTIONS, prompt).strip()
    except Exception as e:
        LOG.warning(f"LLM call failed, keeping the original notes: {e}")
        return notes

    problems = validate(notes, polished)
    if problems:
        LOG.warning("Polished notes failed validation, keeping the original notes:\n- " + "\n- ".join(problems))
        return notes

    return polished


def openai_complete(instructions: str, prompt: str) -> str:
    """Call OpenAI with the key and model from ``commons.settings.OpenAISettings``."""
    from openai import OpenAI

    from commons.settings import OpenAISettings

    settings = OpenAISettings.read()
    client = OpenAI(api_key=settings.api_key)
    response = client.responses.create(model=settings.model, instructions=instructions, input=prompt)

    return response.output_text


def fetch_pull_request_context(notes: str) -> str:
    """Collect title and description of every pull request referenced in the notes via the ``gh`` CLI."""
    context = []

    for number in dict.fromkeys(PR_REFERENCE_PATTERN.findall(notes)):
        try:
            result = subprocess.run(
                ["gh", "pr", "view", number, "--json", "title,body"], capture_output=True, text=True, check=True
            )
            pull_request = json.loads(result.stdout)
            context.append(f"## #{number}: {pull_request['title']}\n\n{pull_request['body']}")
        except (OSError, subprocess.CalledProcessError, json.JSONDecodeError) as e:
            LOG.warning(f"Could not fetch pull request #{number}: {e}")

    return "\n\n".join(context)


def main(argv: list[str] | None = None, complete: Callable[[str, str], str] = openai_complete) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--body", type=Path, required=True, help="Release PR description, updated in place")
    parser.add_argument("--changelog", type=Path, required=True, help="CHANGELOG.md, updated in place")
    args = parser.parse_args(argv)

    body = args.body.read_text().replace("\r\n", "\n")
    changelog = args.changelog.read_text()

    parts = split_body(body)
    if parts is None:
        LOG.warning("Release PR description has no release notes, nothing to do.")
        return 0

    header, notes, footer = parts
    if notes not in changelog:
        LOG.warning(f"Release notes not found in {args.changelog}, nothing to do.")
        return 0

    polished = polish(notes, fetch_pull_request_context(notes), complete)
    if polished == notes:
        return 0

    args.changelog.write_text(changelog.replace(notes, polished, 1))
    args.body.write_text(body.replace(notes, polished, 1))
    LOG.info("Release notes polished.")

    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    sys.exit(main())
