Whatname: Check

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==2.1.3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run checks
        run: poetry run poe check
